= Cálculo de Descontos

Considere que temos um sistema de vendas onde diferentes formas de desconto podem ser implementadas de acordo com as promoções vigentes, como em datas comemorativas. O sistema deve permitir o cálculo do desconto sobre a venda das seguintes maneiras:

- percentual de desconto definido (que pode vir de um banco de dados);
- percentual de desconto progressivo: `valor da compra/25`, não podendo ultrapassar 20% (este são apenas valores arbitrários de exemplo);
- desconto de 15% na data de aniversário do cliente.

O usuário é quem escolhe o tipo de desconto a ser aplicado, não o programa.
O programa deve apenas permitir que seja mudado o algoritmo de cálculo do desconto.

== Responda

1. Qual padrão de projeto pode ser utilizado no desenvolvimento de uma solução? 
   - O padrão de projeto utilizado é o Strategy Pattern. 
2. Como poderíamos implementar estes tipos de desconto sem utilizar Padrões de Projetos? 
   - Poderíamos implementar os diferentes tipos de desconto usando uma série de (if-else) em um único método de cálculo de desconto. Sendo assim esse método receberia um parâmetro indicando o tipo de desconto a ser aplicado e, com base nesse parâmetro, aplicaria a lógica de desconto correspondente.
3. Quais os problemas que tal implementação traria?
   - Baixa taxa de manutenção: Com o tempo, o método calcularDesconto pode crescer, tornando-se difícil de manter e entender. Adicionar novos tipos de desconto exigiria modificar este método, violando o princípio aberto/fechado (OCP) do SOLID.
   - Baixa Extensibilidade: Adicionar novos tipos de desconto implicaria em alterar o método existente, o que pode introduzir erros e complicar os testes.
   - Baixa Reusabilidade: A lógica de desconto estaria acoplada em um único método, dificultando a reutilização de partes específicas da lógica de desconto.
4. Implemente o projeto e envie o link para repositório no GitHub, onde o README deve conter as respostas.

